"""
trace_logger.py
===============
记录 LLM 标注过程中的每一步细节，方便检查模型的思考质量

保存三个文件：
  1. user2_trace.jsonl    — 每个决策点的完整推理记录（逐行 JSON，方便流式查看）
  2. user2_memory.jsonl   — 记忆流的完整变化历史（每次 add 都记一条）
  3. user2_reflections.md — 所有反思内容的人类可读版本（Markdown）

使用方式：
  在 run_user2_annotation.py 中：
    from trace_logger import TraceLogger
    logger = TraceLogger("/root/output")
    
    # 在标注循环中调用：
    logger.log_observation(idx, row, observation, importance)
    logger.log_reflection(idx, questions, reflections)
    logger.log_scoring(idx, row, prompts, raw_scores, final_scores)
    logger.log_memory_event(memory)
"""

import json
import os
import time
from typing import List, Dict, Any, Optional
from pathlib import Path


class TraceLogger:
    """
    详细记录每个决策点的 LLM 推理过程
    """
    
    def __init__(self, output_dir: str = "/root/output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        self.trace_path = self.output_dir / "user2_trace.jsonl"
        self.memory_path = self.output_dir / "user2_memory.jsonl"
        self.reflection_path = self.output_dir / "user2_reflections.md"
        
        # 初始化文件
        # trace: 每个决策点一行 JSON
        self.trace_file = open(self.trace_path, 'w', encoding='utf-8')
        # memory: 每次记忆变动一行
        self.memory_file = open(self.memory_path, 'w', encoding='utf-8')
        # reflections: Markdown 格式，人类可读
        self.reflection_file = open(self.reflection_path, 'w', encoding='utf-8')
        self.reflection_file.write("# LLM Reflections Log\n\n")
        self.reflection_file.write("This file contains all reflections generated by the LLM during annotation.\n")
        self.reflection_file.write("Each reflection is triggered when cumulative importance exceeds the threshold.\n\n")
        self.reflection_file.write("---\n\n")
        
        self.start_time = time.time()
        print(f"  TraceLogger initialized:")
        print(f"    Trace:       {self.trace_path}")
        print(f"    Memory:      {self.memory_path}")
        print(f"    Reflections: {self.reflection_path}")
    
    def log_observation(self, idx: int, row, observation: str, importance: int):
        """记录观察记录和重要性评分"""
        record = {
            "event": "observation",
            "idx": idx,
            "timestamp": str(row['timestamp']),
            "observation": observation,
            "importance": importance,
            "context": {
                "send": int(row.get('send', 0)),
                "jbsteps30": int(row.get('jbsteps30', 0)),
                "jbsteps30pre": int(row.get('jbsteps30pre', 0)),
                "location": str(row.get('dec.location.category', 'unknown')),
                "activity": str(row.get('recognized.activity', 'UNKNOWN')),
                "dosage": float(row.get('dosage', 0)),
            }
        }
        self._write_memory({
            "action": "add_observation",
            "idx": idx,
            "timestamp": str(row['timestamp']),
            "content": observation,
            "importance": importance,
        })
        # 不单独写 trace（等 log_scoring 时一起写）
        return record
    
    def log_reflection(self, idx: int, timestamp: str,
                       questions_prompt: str, questions_response: str,
                       reflections: List[Dict[str, str]]):
        """
        记录反思过程的完整细节
        
        reflections: [{"question": "...", "prompt": "...", "response": "..."}, ...]
        """
        # 写入 trace
        record = {
            "event": "reflection",
            "idx": idx,
            "timestamp": timestamp,
            "questions_prompt": questions_prompt,
            "questions_response": questions_response,
            "reflections": reflections,
        }
        self.trace_file.write(json.dumps(record, ensure_ascii=False) + "\n")
        self.trace_file.flush()
        
        # 写入 memory log
        for ref in reflections:
            self._write_memory({
                "action": "add_reflection",
                "idx": idx,
                "timestamp": timestamp,
                "question": ref.get("question", ""),
                "content": ref.get("response", ""),
            })
        
        # 写入 Markdown（人类可读）
        self.reflection_file.write(f"## Decision Point {idx} — {timestamp}\n\n")
        self.reflection_file.write(f"**Trigger:** Cumulative importance exceeded threshold\n\n")
        self.reflection_file.write(f"### Questions Generated\n\n")
        self.reflection_file.write(f"```\n{questions_response}\n```\n\n")
        
        for i, ref in enumerate(reflections, 1):
            self.reflection_file.write(f"### Reflection {i}\n\n")
            self.reflection_file.write(f"**Question:** {ref.get('question', 'N/A')}\n\n")
            self.reflection_file.write(f"**LLM Response:**\n\n")
            self.reflection_file.write(f"> {ref.get('response', 'N/A')}\n\n")
        
        self.reflection_file.write("---\n\n")
        self.reflection_file.flush()
    
    def log_scoring(self, idx: int, row,
                    prompts: Dict[str, str],
                    raw_samples: Dict[str, List[str]],
                    final_scores: Dict[str, int],
                    memory_context: Dict[str, str]):
        """
        记录评分过程的完整细节
        
        prompts: {"receptivity": "...", "feasibility": "...", "energy": "..."}
        raw_samples: {"receptivity": ["3","4","3","3","4"], ...}
        final_scores: {"receptivity": 3, "feasibility": 4, "energy": 2}
        memory_context: {"recent_observations": "...", "recent_reflections": "..."}
        """
        record = {
            "event": "scoring",
            "idx": idx,
            "timestamp": str(row['timestamp']),
            "context": {
                "send": int(row.get('send', 0)),
                "jbsteps30": int(row.get('jbsteps30', 0)),
                "jbsteps30pre": int(row.get('jbsteps30pre', 0)),
                "location": str(row.get('dec.location.category', 'unknown')),
                "activity": str(row.get('recognized.activity', 'UNKNOWN')),
                "dosage": float(row.get('dosage', 0)),
                "slot": int(row.get('slot', 0)),
            },
            "memory_context": {
                "n_observations": memory_context.get("n_observations", 0),
                "n_reflections": memory_context.get("n_reflections", 0),
                "recent_observations_preview": memory_context.get("recent_observations", "")[:500],
                "recent_reflections_preview": memory_context.get("recent_reflections", "")[:500],
            },
            "scoring": {}
        }
        
        for dim in ["receptivity", "feasibility", "energy"]:
            record["scoring"][dim] = {
                "prompt": prompts.get(dim, "")[:300] + "...",  # 截断存储，避免文件太大
                "prompt_full_length": len(prompts.get(dim, "")),
                "raw_samples": raw_samples.get(dim, []),
                "sample_distribution": dict(self._count(raw_samples.get(dim, []))),
                "final_score": final_scores.get(dim, 0),
            }
        
        elapsed = time.time() - self.start_time
        record["elapsed_seconds"] = round(elapsed, 1)
        
        self.trace_file.write(json.dumps(record, ensure_ascii=False) + "\n")
        self.trace_file.flush()
    
    def log_seed_memory(self, seed_text: str, n_memories: int):
        """记录初始 seed memory"""
        self._write_memory({
            "action": "init_seed_memory",
            "n_memories": n_memories,
            "seed_text": seed_text,
        })
        self.reflection_file.write(f"## Seed Memory\n\n")
        self.reflection_file.write(f"```\n{seed_text}\n```\n\n---\n\n")
        self.reflection_file.flush()
    
    def _write_memory(self, record: dict):
        self.memory_file.write(json.dumps(record, ensure_ascii=False) + "\n")
        self.memory_file.flush()
    
    def _count(self, items):
        from collections import Counter
        return Counter(items)
    
    def close(self):
        """关闭所有文件"""
        self.trace_file.close()
        self.memory_file.close()
        self.reflection_file.close()
        print(f"\n  TraceLogger files saved:")
        print(f"    {self.trace_path} ({self.trace_path.stat().st_size / 1024:.1f} KB)")
        print(f"    {self.memory_path} ({self.memory_path.stat().st_size / 1024:.1f} KB)")
        print(f"    {self.reflection_path} ({self.reflection_path.stat().st_size / 1024:.1f} KB)")


def print_trace_summary(trace_path: str = "/root/output/user2_trace.jsonl"):
    """
    读取 trace 文件并打印人类可读的摘要
    可以在标注完成后运行来快速查看结果
    
    Usage:
        python3 -c "from trace_logger import print_trace_summary; print_trace_summary()"
    """
    import json
    
    scoring_events = []
    reflection_events = []
    
    with open(trace_path, 'r', encoding='utf-8') as f:
        for line in f:
            record = json.loads(line)
            if record["event"] == "scoring":
                scoring_events.append(record)
            elif record["event"] == "reflection":
                reflection_events.append(record)
    
    print(f"{'='*70}")
    print(f"TRACE SUMMARY: {len(scoring_events)} scoring events, {len(reflection_events)} reflections")
    print(f"{'='*70}")
    
    # 打印每个决策点的评分和上下文
    print(f"\n{'idx':>4} | {'time':>19} | {'send':>4} | {'steps':>5} | {'R':>1} {'F':>1} {'E':>1} | {'R_samples':>15} | {'F_samples':>15} | {'E_samples':>15} | loc")
    print("-" * 120)
    
    for ev in scoring_events:
        idx = ev["idx"]
        ts = ev["timestamp"][:19]
        ctx = ev["context"]
        sc = ev["scoring"]
        
        r_samples = sc["receptivity"]["raw_samples"]
        f_samples = sc["feasibility"]["raw_samples"]
        e_samples = sc["energy"]["raw_samples"]
        
        print(f"{idx:>4} | {ts} | {ctx['send']:>4} | {ctx['jbsteps30']:>5} | "
              f"{sc['receptivity']['final_score']} {sc['feasibility']['final_score']} {sc['energy']['final_score']} | "
              f"{str(r_samples):>15} | {str(f_samples):>15} | {str(e_samples):>15} | "
              f"{ctx['location'][:10]}")
    
    # 打印反思
    if reflection_events:
        print(f"\n{'='*70}")
        print(f"REFLECTIONS ({len(reflection_events)} total)")
        print(f"{'='*70}")
        
        for ev in reflection_events:
            print(f"\n--- Decision Point {ev['idx']} ({ev['timestamp']}) ---")
            for ref in ev.get("reflections", []):
                q = ref.get("question", "?")[:80]
                r = ref.get("response", "?")[:120]
                print(f"  Q: {q}")
                print(f"  A: {r}")
    
    # 统计
    print(f"\n{'='*70}")
    print(f"SCORE DISTRIBUTIONS")
    print(f"{'='*70}")
    
    from collections import Counter
    for dim in ["receptivity", "feasibility", "energy"]:
        all_scores = [ev["scoring"][dim]["final_score"] for ev in scoring_events]
        dist = Counter(all_scores)
        mean = sum(all_scores) / len(all_scores) if all_scores else 0
        print(f"  {dim:>15}: mean={mean:.2f}, dist={dict(sorted(dist.items()))}")


if __name__ == "__main__":
    # 如果直接运行，打印已有 trace 的摘要
    import sys
    path = sys.argv[1] if len(sys.argv) > 1 else "/root/output/user2_trace.jsonl"
    if os.path.exists(path):
        print_trace_summary(path)
    else:
        print(f"Trace file not found: {path}")
        print("Run the annotation first, then use this to inspect results.")
